import { Router } from "express";
import cscRoutes from "./csc.js";
import hsnRoutes from "./hsn.js";
import sacRoutes from "./sac.js";
import rtoRoutes from "./rto.js";
import userRoutes from "./user.js";
import companyRoutes from "./company.js";
import manufacturerRoutes from "./manufacturer.js";
import financerRoutes from "./financer.js";
import vehicleMasterRoutes from "./vehicleMaster.js";
import customerRoutes from "./customer.js";
import enquiryRoutes from "./enquiry.js";
import vehiclePriceRoutes from "./vehiclePrice.js";
import quotationRoutes from "./quotation.js";
import bookingRoutes from "./booking.js";
import vehicleInventoryRoutes from "./vehicleInventory.js";
import partsMasterRoutes from "./partsMaster.js";
import sparesInventoryRoutes from "./sparesInventory.js";
import jobOrderRoutes from "./jobOrder.js";
import jobOrderLogRoutes from "./jobOrderLog.js";
import ledgerRoutes from "./ledger.js";
import reportRoutes from "./reports.js";
import supplierRoutes from "./supplier.js";
import purchaseChallanRoutes from "./purchaseChallan.js";
import purchaseInvoiceRoutes from "./purchaseInvoice.js";
import purchaseSpareInvoiceRoutes from "./purchaseSpareInvoice.js";
import saleInvoiceRoutes from "./saleInvoice.js";
import saleRegisterRoutes from "./saleRegister.js";
import soldVehicleRoutes from "./soldVehicle.js";
import jobCodeRoutes from "./jobCode.js";
import estimateRoutes from "./estimate.js";
import jobInvoiceRoutes from "./jobInvoice.js";
import saleSpareInvoiceRoutes from "./saleSpareInvoice.js";
import gstVerifyRoutes from "./gstVerify.js";
import pdfGenerateRoutes from "./pdfGenerate.js";
import telecmiRoutes from "./telecmi-webhooks.js";
import dashboardRoutes from "./dashboard.js";
import ledgerDetailRoutes from "./ledgerDetail.js";
import whatsappRoutes from "./whatsup.js";
import optionsListRoutes from "./optionsList.js";
import materialIssueRoutes from "./materialIssue.js";
import stockCheckRoutes from "./stockCheck.js";
import purchaseReturnRoutes from "./purchaseReturn.js";
import accessoriesRoutes from "./accessories.js";
import departmentRoutes from "./department.js";
import subDealerRoutes from "./subDealer.js";
import smsRoutes from "./sms.js";
import sendSmsRoutes from "./sendSms.js";
import promotionsRoutes from "./promotions.js";
import idGenerateRoutes from "./idGenerate.js";
import idCreationRoutes from "./idCreation.js";
import activityRoutes from "./activity.js";
import uploadRoutes from "./upload.js";
import frameNumberRoutes from "./frameNumber.js";

const router = Router();

router.use("/csc", cscRoutes);
router.use("/hsn", hsnRoutes);
router.use("/sac", sacRoutes);
router.use("/rto", rtoRoutes);
router.use("/user", userRoutes);
router.use("/company", companyRoutes);
router.use("/manufacturer", manufacturerRoutes);
router.use("/financer", financerRoutes);
router.use("/vehicleMaster", vehicleMasterRoutes);
router.use("/customer", customerRoutes);
router.use("/enquiry", enquiryRoutes);
router.use("/vehiclePrice", vehiclePriceRoutes);
router.use("/quotation", quotationRoutes);
router.use("/booking", bookingRoutes);
router.use("/vehicleInventory", vehicleInventoryRoutes);
router.use("/partsMaster", partsMasterRoutes);
router.use("/sparesInventory", sparesInventoryRoutes);
router.use("/jobOrder", jobOrderRoutes);
router.use("/jobOrderLog", jobOrderLogRoutes);
router.use("/ledger", ledgerRoutes);
router.use("/reports", reportRoutes);
router.use("/supplier", supplierRoutes);
router.use("/purchaseChallan", purchaseChallanRoutes);
router.use("/purchaseInvoice", purchaseInvoiceRoutes);
router.use("/purchaseSpareInvoice", purchaseSpareInvoiceRoutes);
router.use("/saleInvoice", saleInvoiceRoutes);
router.use("/saleRegister", saleRegisterRoutes);
router.use("/vehicle", soldVehicleRoutes);
router.use("/jobCode", jobCodeRoutes);
router.use("/estimate", estimateRoutes);
router.use("/jobInvoice", jobInvoiceRoutes);
router.use("/saleSpareInvoice", saleSpareInvoiceRoutes);
router.use("/gstVerify", gstVerifyRoutes);
router.use("/pdfGenerate", pdfGenerateRoutes);
router.use("/telecmi", telecmiRoutes);
router.use("/dashboard", dashboardRoutes);
router.use("/ledgerDetail", ledgerDetailRoutes);
router.use("/whatsapp", whatsappRoutes);
router.use("/options", optionsListRoutes);
router.use("/materialIssue", materialIssueRoutes);
router.use("/stockCheck", stockCheckRoutes);
router.use("/purchaseReturn", purchaseReturnRoutes);
router.use("/accessories", accessoriesRoutes);
router.use("/department", departmentRoutes);
router.use("/subDealer", subDealerRoutes);
router.use("/sms", smsRoutes);
router.use("/sendSms", sendSmsRoutes);
router.use("/promotions", promotionsRoutes);
router.use("/idGenerate", idGenerateRoutes);
router.use("/idCreation", idCreationRoutes);
router.use("/activity", activityRoutes);
router.use("/upload", uploadRoutes);
router.use("/frameNumber", frameNumberRoutes);

export default router;
