import { Router } from "express";
import cscRoutes from "./csc.js";
import hsnRoutes from "./hsn.js";
import sacRoutes from "./sac.js";
import rtoRoutes from "./rto.js";
import userRoutes from "./user.js";
import companyRoutes from "./company.js";
import manufacturerRoutes from "./manufacturer.js";
import financerRoutes from "./financer.js";
import vehicleMasterRoutes from "./vehicleMaster.js";
import customerRoutes from "./customer.js";
import enquiryRoutes from "./enquiry.js";
import vehiclePriceRoutes from "./vehiclePrice.js";
import quotationRoutes from "./quotation.js";
import bookingRoutes from "./booking.js";
import vehicleInventoryRoutes from "./vehicleInventory.js";
import partsMasterRoutes from "./partsMaster.js";
import sparesInventoryRoutes from "./sparesInventory.js";
import jobOrderRoutes from "./jobOrder.js";
import jobOrderLogRoutes from "./jobOrderLog.js";
import ledgerRoutes from "./ledger.js";
import reportRoutes from "./reports.js";
import supplierRoutes from "./supplier.js";
import purchaseChallanRoutes from "./purchaseChallan.js";
import purchaseInvoiceRoutes from "./purchaseInvoice.js";
import purchaseSpareInvoiceRoutes from "./purchaseSpareInvoice.js";
import saleInvoiceRoutes from "./saleInvoice.js";
import saleRegisterRoutes from "./saleRegister.js";
import soldVehicleRoutes from "./soldVehicle.js";
import jobCodeRoutes from "./jobCode.js";
import estimateRoutes from "./estimate.js";
import jobInvoiceRoutes from "./jobInvoice.js";
import saleSpareInvoiceRoutes from "./saleSpareInvoice.js";

const router = Router();

router.use("/csc", cscRoutes);
router.use("/hsn", hsnRoutes);
router.use("/sac", sacRoutes);
router.use("/rto", rtoRoutes);
router.use("/user", userRoutes);
router.use("/company", companyRoutes);
router.use("/manufacturer", manufacturerRoutes);
router.use("/financer", financerRoutes);
router.use("/vehicleMaster", vehicleMasterRoutes);
router.use("/customer", customerRoutes);
router.use("/enquiry", enquiryRoutes);
router.use("/vehiclePrice", vehiclePriceRoutes);
router.use("/quotation", quotationRoutes);
router.use("/booking", bookingRoutes);
router.use("/vehicleInventory", vehicleInventoryRoutes);
router.use("/partsMaster", partsMasterRoutes);
router.use("/sparesInventory", sparesInventoryRoutes);
router.use("/jobOrder", jobOrderRoutes);
router.use("/jobOrderLog", jobOrderLogRoutes);
router.use("/ledger", ledgerRoutes);
router.use("/reports", reportRoutes);
router.use("/supplier", supplierRoutes);
router.use("/purchaseChallan", purchaseChallanRoutes);
router.use("/purchaseInvoice", purchaseInvoiceRoutes);
router.use("/purchaseSpareInvoice", purchaseSpareInvoiceRoutes);
router.use("/saleInvoice", saleInvoiceRoutes);
router.use("/saleRegister", saleRegisterRoutes);
router.use("/soldVehicle", soldVehicleRoutes);
router.use("/jobCode", jobCodeRoutes);
router.use("/estimate", estimateRoutes);
router.use("/jobInvoice", jobInvoiceRoutes);
router.use("/saleSpareInvoice", saleSpareInvoiceRoutes);

export default router;
